# Generated by Django 5.2 on 2025-04-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlFuncArgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('reserve_datetime1', models.DateTimeField(null=True)),
                ('reserve_datetime2', models.DateTimeField(null=True)),
                ('is_test', models.BooleanField(default=True)),
                ('title_ids', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(db_index=True, default='wait', max_length=10)),
                ('func_args', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.crawlfuncargs')),
            ],
        ),
    ]
