# Generated by Django 5.2 on 2025-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenedBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('driver_number', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
