# Generated by Django 5.2 on 2025-04-18 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlfuncargs',
            name='title_ids',
        ),
        migrations.AddField(
            model_name='job',
            name='process_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='func_args',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.crawlfuncargs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='wait', max_length=10),
        ),
    ]
