# Generated by Django 5.2 on 2025-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_title_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
