# Generated by Django 5.2 on 2025-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_crawlfuncargs_title_ids_job_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
