# Generated by Django 5.2 on 2025-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_job_customer_id_alter_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
