# Generated by Django 5.2 on 2025-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_job_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlfuncargs',
            name='reserve_datetime1',
        ),
        migrations.RemoveField(
            model_name='crawlfuncargs',
            name='reserve_datetime2',
        ),
        migrations.AddField(
            model_name='crawlfuncargs',
            name='reserve_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='crawlfuncargs',
            name='reserve_time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
