# Generated by Django 5.2 on 2025-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_job_end_date_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
