# Generated by Django 5.2 on 2025-04-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_crawlfuncargs_reserve_datetime1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='crawlfuncargs',
            name='title_ids',
            field=models.TextField(blank=True),
        ),
    ]
