# Generated by Django 5.2 on 2025-04-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_job_options_crawlfuncargs_title_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
