# Generated by Django 5.2 on 2025-04-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_job_driver_process_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlfuncargs',
            name='title_ids',
        ),
    ]
