# Generated by Django 5.2 on 2025-04-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_crawlfuncargs_title_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenedBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
