# Generated by Django 5.2 on 2025-04-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_openedbrowser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='func_args',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.crawlfuncargs'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('wait', 'Wait'), ('finish', 'Finish'), ('close', 'Close')], db_index=True, default='wait', max_length=10),
        ),
    ]
