# Generated by Django 5.2 on 2025-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_job_func_args_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedbrowser',
            name='driver_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
