# Generated by Django 5.2 on 2025-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_openedbrowser_driver_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openedbrowser',
            name='driver_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
