# Generated by Django 5.1.6 on 2025-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_customer_time_customer_time1_customer_time2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='date2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='date3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='date4',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
