# Generated by Django 5.1.6 on 2025-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customer_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vehicle_cat',
            field=models.CharField(choices=[('', '-- انتخاب کنید'), ('khodro', 'سواری شخصی'), ('khodro_dolati', 'سواری دولتی'), ('vanet', 'وانت شخصی'), ('vanet_doulati', 'وانت دولتی'), ('motor', 'موتور سیکلت'), ('taxi', 'تاکسی')], default='', max_length=150),
        ),
    ]
