# Generated by Django 5.1.6 on 2025-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customer_vehicle_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelak',
            name='letter_value',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pelak',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
