# Generated by Django 5.1.6 on 2025-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_pelak_letter_value_alter_pelak_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='browser_counts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
