# Generated by Django 5.1.6 on 2025-03-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customer_browser_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='browser_counts',
        ),
    ]
