# Generated by Django 5.1.6 on 2025-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customer_browser_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='browser_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
