# Generated by Django 5.1.6 on 2025-03-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customer_browser_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='browser_count',
        ),
        migrations.AddField(
            model_name='customer',
            name='color_classes',
            field=models.TextField(blank=True),
        ),
    ]
