# Generated by Django 5.1.7 on 2025-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customer_browser_count_customer_color_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='finall_message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
