# Generated by Django 5.1.7 on 2025-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customer_finall_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='finall_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
