# Generated by Django 5.2 on 2025-04-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APSchedulerJob',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('next_run_time', models.FloatField(blank=True, null=True)),
                ('job_state', models.BinaryField()),
            ],
            options={
                'db_table': 'apscheduler_jobs',
                'managed': False,
            },
        ),
    ]
