# Generated by Django 5.2 on 2025-04-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlFuncArgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('reserve_date', models.CharField(blank=True, max_length=30)),
                ('reserve_time', models.CharField(blank=True, max_length=30)),
                ('is_test', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('wait', 'Wait'), ('finish', 'Finish'), ('close', 'Close')], db_index=True, default='wait', max_length=10)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('driver_process_id', models.IntegerField(blank=True, null=True)),
                ('func_args', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.crawlfuncargs')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
